develop:
    only:
        - develop
    script:
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
        - docker pull registry.orr.noaa.gov/gnome/oillibrary:develop
        - docker tag registry.orr.noaa.gov/gnome/oillibrary:develop oillibrary
        - docker build -f dockerfile . -t registry.orr.noaa.gov/gnome/oillibraryapi:develop
        - docker push registry.orr.noaa.gov/gnome/oillibraryapi:develop
    tags:
        - shell
        - build
        
master:
    only:
        - master
    script:
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
        - docker pull registry.orr.noaa.gov/gnome/oillibrary:master
        - docker tag registry.orr.noaa.gov/gnome/oillibrary:master oillibrary
        - docker build -f dockerfile . -t registry.orr.noaa.gov/gnome/oillibraryapi:master
        - docker push registry.orr.noaa.gov/gnome/oillibraryapi:master
    tags:
        - shell
        - build

production:
    only:
        - production
    script:
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
        - docker pull registry.orr.noaa.gov/gnome/oillibrary:production 
        - docker tag registry.orr.noaa.gov/gnome/oillibrary:production oillibrary
        - docker build -f dockerfile . -t registry.orr.noaa.gov/gnome/oillibraryapi:production
        - docker push registry.orr.noaa.gov/gnome/oillibraryapi:production
    tags:
        - shell
        - build
