""" Setup file.
"""
import os
import glob
import shutil

from setuptools import setup, find_packages
from distutils.command.clean import clean

# could run setup from anywhere
here = os.path.abspath(os.path.dirname(__file__))
README = open(os.path.join(here, 'README.md')).read()
pkg_name = 'oil_library_api'
pkg_version = '0.0.3'


def clean_files():
    src = os.path.join(here, r'oil_library_api')
    to_rm = glob.glob(os.path.join(src, r'*.pyc'))
    to_rm.extend([os.path.join(here, '{0}.egg-info'.format(pkg_name)),
                  os.path.join(here, 'build'),
                  os.path.join(here, 'dist')])

    for f in to_rm:
        try:
            if os.path.isdir(f):
                shutil.rmtree(f)
            else:
                os.remove(f)
        except:
            pass

        print "Deleting {0} ..".format(f)


class cleanall(clean):
    description = "cleans files generated by 'develop'"

    def run(self):
        clean.run(self)
        clean_files()


setup(name=pkg_name,
      version=pkg_version,
      description=('{}: {}'.format(pkg_name,
                                   'A simple web server to access '
                                   'the NOAA oil library')),
      classifiers=["Programming Language :: Python",
                   "Framework :: Pylons",
                   "Topic :: Internet :: WWW/HTTP",
                   "Topic :: Internet :: WWW/HTTP :: WSGI :: Application"
                   ],
      keywords="adios gnome oilspill weathering trajectory modeling",
      author='ADIOS/GNOME team at NOAA ORR',
      author_email='orr.gnome@noaa.gov',
      package_data={'oil_library_api': ['tests/*.py']},
      url='',
      cmdclass={'cleanall': cleanall,
                },
      packages=find_packages(),
      include_package_data=True,
      zip_safe=False,
      entry_points=('[paste.app_factory]\n'
                    '  main = oil_library_api:main\n'
                    '[console_scripts]\n'
                    '  export_oil_library = oil_library_api.scripts.reports:export\n'
                    '  audit_oil_library = oil_library_api.scripts.reports:audit\n'
                    '  audit_oil_cuts = oil_library_api.scripts.reports:audit_cuts\n'
                    '  plot_oil_viscosity = oil_library_api.scripts.plot_oil_viscosity:main\n'
                    ),
      paster_plugins=['pyramid'],
      )
